@startuml
title Warm House System. Modules Control Service Component Diagram

top to bottom direction

!includeurl ./templates/C4_Component.puml

System_Boundary(WarmHouseSystemBoundary, "Warm House System") {
  ContainerDb(ModuleServicesDb, "Module Services DB", "Postgres", "Расшаренная БД сервисов модулей и пользовательских сценариях")
  Container(ModulesControlService, "Modules Control Service", "Java", "Сервис управления модулями и командами модулей")
  Container(MobileClientApiGateway, "Mobile Client API Gateway", "KrakenD", "Шлюз для маршрутизации запросов, аутентификации, авторизации и SSL завершения")
  Container(ModuleControlMessagesAsyncHandlingService, "Module Control Messages Async Handling Service", "Java", "Сервис асинхронной обработки сообщений управления модулями")
  ContainerQueue(MessageBroker, "Message Broker", "RabbitMQ", "Брокер сообщений для асинхронных операций")
}

Container(ModulesControlService, "Modules Control Service", "Java") {
  Component(ModulesControlController, "Modules Control Controller", "Controller", "Обрабатывает запросы для управления модулями и исполнения команд")
  Component(UserModulesController, "User Modules Controller", "Controller","Обрабатывает запросы для работы с модулями пользователя")
  Component(UserHousesController, "User Houses Controller", "Controller","Обрабатывает управлением домов пользователя")
 
  Component(GetModulesQueryHandler, "Get Modules Query Handler", "CQRS Handler, ORM", "Обработчик запроса получения модулей с командами")
  Component(PublishHandleControlCommandHandler, "Publish Handle Control Command Handler", "CQRS Handler", "Обработчик публикации для обработки команды управления")
  
  Component(GetUserModulesQueryHandler, "Get UserModules Query Handler", "CQRS Handler, ORM", "Обработчик запроса получения модулей пользователя")
  Component(RegisterUserModuleCommandHandler, "Register User Module Command Handler", "CQRS Handler, ORM", "Обработчик команды регистрации модуля")
  Component(RemoveUserModuleCommandHandler, "Remove User Module Command Handler", "CQRS Handler, ORM", "Обработчик команды удаления модуля")
  Component(UpdateUserModuleCommandHandler, "Update User Module Command Handler", "CQRS Handler, ORM", "Обработчик команды обновления модуля")
  Component(UpdateUserModuleStatusCommandHandler, "Update User Module Status Command Handler", "CQRS Handler, ORM", "Обработчик команды обновления статуса модуля")
  
  Component(CreateUserHouseCommandHandler, "Create User House Command Handler", "CQRS Handler, ORM", "Обработчик команды создания дома пользователя")
  Component(UpdateUserHouseCommandHandler, "Update User House Command Handler", "CQRS Handler, ORM", "Обработчик команды обновления дома пользователя")
  Component(DeleteUserHouseCommandHandler, "Delete User House Command Handler", "CQRS Handler, ORM", "Обработчик команды удаления дома пользователя")

  Component(PublishCreateControlModuleCommandHandler, "Publish Create Control Module Command Handler", "CQRS Handler", "Обработчик публикации команды создания модуля управления")
  Component(PublishDeleteControlModuleCommandHandler, "Publish Delete Control Module Command Handler", "CQRS Handler", "Обработчик публикации команды удаления модуля управления")

  Component(MessagesProducer, "Messages Producer", "Producer, RabbitMQ Client","Публикует команды и запросы в очередь")
}

Rel(ModulesControlController, GetModulesQueryHandler,"Использует")
Rel(ModulesControlController, PublishHandleControlCommandHandler,"Использует")

Rel(UserModulesController, GetUserModulesQueryHandler,"Использует")
Rel(UserModulesController, RegisterUserModuleCommandHandler,"Использует")
Rel(UserModulesController, RemoveUserModuleCommandHandler,"Использует")
Rel(UserModulesController, UpdateUserModuleCommandHandler,"Использует")
Rel(UserModulesController, UpdateUserModuleStatusCommandHandler,"Использует")

Rel(UserHousesController, CreateUserHouseCommandHandler,"Использует")
Rel(UserHousesController, UpdateUserHouseCommandHandler,"Использует")
Rel(UserHousesController, DeleteUserHouseCommandHandler,"Использует")

Rel(GetModulesQueryHandler, ModuleServicesDb, "Использует", "TCP")
Rel(PublishHandleControlCommandHandler, MessagesProducer,"Использует")

Rel(RegisterUserModuleCommandHandler, ModuleServicesDb,"Использует")
Rel(RegisterUserModuleCommandHandler, PublishCreateControlModuleCommandHandler,"Использует")

Rel(RemoveUserModuleCommandHandler, ModuleServicesDb,"Использует")
Rel(RemoveUserModuleCommandHandler, PublishDeleteControlModuleCommandHandler,"Использует")

Rel(PublishCreateControlModuleCommandHandler, MessagesProducer,"Использует")
Rel(PublishDeleteControlModuleCommandHandler, MessagesProducer,"Использует")

Rel(MessagesProducer, MessageBroker,"Публикует сообщения в", "AMQP")

Rel(UpdateUserModuleStatusCommandHandler, ModuleServicesDb,"Использует")

Rel(CreateUserHouseCommandHandler, ModuleServicesDb,"Использует", "TCP")
Rel(UpdateUserHouseCommandHandler, ModuleServicesDb,"Использует", "TCP")
Rel(DeleteUserHouseCommandHandler, ModuleServicesDb,"Использует", "TCP")

Rel(ModuleControlMessagesAsyncHandlingService, UserModulesController,"Изменяет статус устройства пользователя в","JSON, REST, mTLS, HTTPS")

@enduml