@startuml
title Warm House System ERP Diagram


top to bottom direction

!include ./templates/C4_Component.puml

class User {
+ GUID Id
+ string FirstName
+ string SecondName
+ string PatronymicName
+ string Username
+ string Email
+ DateOnly Birthday
}

class ModuleCommand {
+ GUID Id 
+ string Name
+ string ProtocolType
+ bool IsUserScriptsAvailable
+ string CommandSystemType
}

class ModuleToCommand {
+ GUID ModuleId
+ GUID ModuleCommandId
}

class Module {
+ GUID Id
+ string Name
+ string DeviceSystemType
+ string ProtocolType
+ ModuleCommand[] Commands
}

class UserModule {
+ GUID Id
+ string Name
+ string Status
+ string SerialNumber
+ string ProtocolType
+ string RegistrationInfo
+ GUID UserId
+ GUID ModuleId
+ GUID UserHouseId
}

class UserHouse {
+ GUID Id
+ string Name
+ GUID UserId
}

class UserHouse {
+ GUID Id
+ string Name
+ GUID UserId
}

class UserModuleScript {
+ GUID Id
+ string Name
+ GUID UserId
+ jsonb Script
}

class ModuleRegistration {
+ GUID Id 
+ GUID UserId
+ GUID UserModuleId 
+ string ProtocolType
+ jsonb ProtocolDeviceParameters 
}

UserModule "0..*" --* "1..1" Module
Module "1..1" *-- "0..1" ModuleToCommand
ModuleToCommand "0..1" --* "1..1" ModuleCommand
UserModule "0..1" -- "0..1" UserHouse

UserModule "0..*" --* "1..1" User
UserHouse "0..*" --* "1..1" User
UserModuleScript "0..*" --* "1..1" User

ModuleRegistration "0..*" --* "1..1" User
ModuleRegistration "0..*" --* "1..1" UserModule

@enduml